Document: login-monitor
Title: Debian login-monitor Manual
Author: <insert document author here>
Abstract: This manual describes what login-monitor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/login-monitor/login-monitor.sgml.gz

Format: postscript
Files: /usr/share/doc/login-monitor/login-monitor.ps.gz

Format: text
Files: /usr/share/doc/login-monitor/login-monitor.text.gz

Format: HTML
Index: /usr/share/doc/login-monitor/html/index.html
Files: /usr/share/doc/login-monitor/html/*.html
